### PR TITLE
Edit colab notebook

### PR DESCRIPTION
**Pull request by amrzv**
Hi!
- removed `import glob` because it isn't used
- simplified downloading and unzipping pretrained model into two lines of code (using `gdown`)
- added `map_location=device` in `torch.load` that is in `load_model` method; it fixed an error when running notebook in CPU mode
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
- changed `figsize=(8, 4)` for better proportions; removed `fig.axes.get_yaxis().set_visible(False)` because it does nothing.
- prettified a little (according pep8)
- updated colab url to notebook from repo instead one from gdrive; added colab badge.

### CODE REVIEW

**Comment by jiupinjia** [comment]
Wow, thanks for your amazing fixes! Some suggestions are really helpful and I really learned a lot! I am now merging your pull request to my main branch. Any further updates on your end will be welcome!

**Comment by amrzv** [comment]
Thanks for your amazing project, I was glad to help a little.

**Comment by ayushblaze** [comment]
Glad to have contributed a little :)

**Comment by jiupinjia** [comment]
@AYUSHBlaze 
Cheers!

**Pull request merged**
